version: "3.7"

services:
  app:
    image: nginx_ssh_mysql_php74
    build:
      context: .
      dockerfile: Dockerfile
      args:
        SSH_USERNAME: ducdat
        SSH_PASSWORD: password
    environment:
      MYSQL_ROOT_PASSWORD: password
    container_name: nginx_ssh_mysql_php74
    ports:
      - "7767:22"
      - "7768:80"
      - "7769:3306"
    restart: always
